language: ruby
rvm:
- 2.2.1
- 2.2.0
gemfile:
- Gemfile
cache: bundler
before_script:
- mkdir /home/travis/build/whatisinternet/spark_plugs/spec/dummy/tmp
- mkdir /home/travis/build/whatisinternet/spark_plugs/spec/dummy/tmp/cache
script:
- bundle install
- rake db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: DDX0in/RU35B4ijmV0KjmVOGnzA4QWbrIIdKkxAoKuTan/4nLnaeazlS5b4MaWeVSLyMmX7XRfJPn0rRehnrYEFbTVME8vgNarbOV7hJmGMUXgN6JoPIfTQDaIjHxXM2gCfwnIOGqqQVFM/mbkz8xYTz2Mipi2YNtqaP6/1EoKo=
  gem: spark_plugs
  on:
    tags: true
    repo: whatisinternet/spark_plugs
