language: ruby

rvm:
- 2.2.0
- 2.1.5

gemfile:
  - Gemfile

cache: bundler

script:
  - mkdir /home/travis/build/whatisinternet/spark_plugs/spec/dummy/tmp/cache
  - bundle install
  - rake db:migrate RAILS_ENV=test
  - bundle exec rspec
