require 'rails_helper'
require 'faker'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module SparkPlugs
  RSpec.describe StaticPagesController, type: :controller do
    routes { SparkPlugs::Engine.routes }

    before :all do
      Rails.cache.clear
      @static_page = FactoryGirl.create :spark_plugs_static_page
    end

    # This should return the minimal set of attributes required to create a valid
    # StaticPage. As you add validations to StaticPage, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      FactoryGirl.build(:spark_plugs_static_page).attributes.symbolize_keys
    }

    let(:invalid_attributes) {
      { page: Faker::Lorem.characters(1) }
    }

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # StaticPagesController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe "GET #show" do
      it "assigns the requested static_page as @static_page" do
        get :show, {:id => @static_page.to_param, page: @static_page.page.to_param}, valid_session
        expect(assigns(:static_page)).to eq(@static_page)
      end
    end

    describe "GET #new" do
      it "assigns a new static_page as @static_page" do
        get :new, {}, valid_session
        expect(assigns(:static_page)).to be_a_new(StaticPage)
      end
    end

    describe "GET #edit" do
      it "assigns the requested static_page as @static_page" do
        get :edit, {:id => @static_page.to_param}, valid_session
        expect(assigns(:static_page)).to eq(@static_page)
      end
    end

    describe "POST #create" do
      context "with valid params" do
        it "creates a new StaticPage" do
          expect {
            post :create, {:static_page => valid_attributes}, valid_session
          }.to change(StaticPage, :count).by(1)
        end

        it "assigns a newly created static_page as @static_page" do
          post :create, {:static_page => valid_attributes}, valid_session
          expect(assigns(:static_page)).to be_a(StaticPage)
          expect(assigns(:static_page)).to be_persisted
        end

        it "redirects to the created static_page" do
          post :create, {:static_page => valid_attributes}, valid_session
          expect(response).to redirect_to(StaticPage.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved static_page as @static_page" do
          post :create, {:static_page => invalid_attributes}, valid_session
          expect(assigns(:static_page)).to be_a_new(StaticPage)
        end

        it "re-renders the 'new' template" do
          post :create, {:static_page => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) {
          { page: "queiofsaksjadfljd" }
        }

        it "updates the requested static_page" do
          static_page = StaticPage.create! valid_attributes
          put :update, {:id => @static_page.to_param, :static_page => new_attributes}, valid_session
          static_page.reload
          expect(assigns(:page)).to eq(@page)
        end

        it "assigns the requested static_page as @static_page" do
          put :update, {:id => @static_page.to_param, :static_page => valid_attributes}, valid_session
          expect(assigns(:static_page)).to eq(@static_page)
        end

        it "redirects to the static_page" do
          put :update, {:id => @static_page.to_param, :static_page => valid_attributes}, valid_session
          expect(response).to redirect_to(@static_page)
        end
      end

      context "with invalid params" do
        it "assigns the static_page as @static_page" do
          put :update, {:id => @static_page.to_param, :static_page => invalid_attributes}, valid_session
          expect(assigns(:static_page)).to eq(@static_page)
        end

        it "re-renders the 'edit' template" do
          put :update, {:id => @static_page.to_param, :static_page => invalid_attributes}, valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested static_page" do
        expect {
          delete :destroy, {:id => @static_page.to_param}, valid_session
        }.to change(StaticPage, :count).by(-1)
      end

      it "redirects to the static_pages list" do
        delete :destroy, {:id => @static_page.to_param}, valid_session
        expect(response).to redirect_to(static_pages_url)
      end
    end

  end
end
